#include <stdio.h>
#include "openssl/evp.h"
#include <string.h>

#define MAX_LENGTH 16 // A global variable t define max-length

int main (int argc, const char *argv[])
{
	/* This variable is used to store the ciphertext provided to you. Make sure to use the proper format, eg. the hex 'd23a' would be written as {0xd2,0x3a} in C: done */
	unsigned char ciphertxt[] = {0x20, 0x75, 0x38, 0x6b, 0x75, 0xee, 0xd8, 0xb4, 0xf2, 0xb4, 0xa9, 0xc9, 0xb7, 0x69, 0x67, 0xd0, 0x57, 0xb4, 0xa4, 0x41, 0xd3, 0x49, 0xc1, 0x5d, 0xd4, 0xb8, 0xbf, 0x4b, 0x87, 0x44, 0x5a, 0x9e};

	// This is the plaintext that we are encrypting. Do not change it as it may result in a different ciphertext
	char plaintext[]= "This is a top secret";

	// Pointer fp used to point to the English words file provided along.
	FILE *fp;

	// The initialization Vector is set to 0
	unsigned char iv[] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};

	// Output buffer set to 1024 size
	unsigned char outbuf [1024];

	// Some other variables that are used in the program
	int outlen = 0, tmplen = 0;
	/* You may want to declare some additional variables to be used as flags*/

	EVP_CIPHER_CTX ctx;
	//Modified by me: open the txt file
	char *mode = "r";
	char fileName[] = "words.txt"; 
	fp = fopen(fileName, mode);

	if (fp == NULL /* Use this statement to check is the words.txt file can be opened in 'r' permission: done */)
	{
		/* Print a statement if the above condition is not met: done */
		fprintf(stderr, "Can't open input file in.list!\n");
		return 0;
	}

	char key [MAX_LENGTH]; //array to store the key getting from the dictionary

	while (fgets(key, MAX_LENGTH, fp) != NULL)
	{
		for(int i = 0; i < MAX_LENGTH; i++)
		{
			if (key[i] == '\n' || key[i] == 0 ) //when key is less than 16 characters, the extra left part is filled with " "
			{
				for (int j = i; j < strlen(key); j++)
				{
					key[j] = ' ';
				}
				break;
			}
		}

		// Use the EVP library to initialize cipher
		EVP_CIPHER_CTX_init (&ctx);

		// Use the EVP library to encrypt the cipher
		EVP_EncryptInit_ex (&ctx, EVP_aes_128_cbc(), NULL, key, iv);

		// Checking to see if EVP_EncryptUpdate is valid or not
		if (!EVP_EncryptUpdate (&ctx, outbuf, &outlen, plaintext, strlen(plaintext)))
		{
			/*Print Out a relevant Error Messege: done*/
			fprintf(stderr, "Impossible to encrypt the bytes from the plaintext into the buffer\n");
			return 0;
		}

		// Buffer passed to EVP_EncryptFinal() must be after data just encrypted to avoid overwriting it

		// Checking to see if !EVP_EncryptFinal_ex is valid or not
		if (!EVP_EncryptFinal_ex (&ctx, outbuf + outlen, &tmplen))
		{
			/*Print Out a relevant Error Messege: done*/
			fprintf(stderr, "The buffer is not empty\n");
			return 0;
		}

		outlen += tmplen;

		EVP_CIPHER_CTX_cleanup (&ctx);

		//print curret key and its corresponding ciphertext
		printf ("The key is : %s       The Corresponding Cipher Text Is:  ", key); 

		for(int j = 0; j < outlen; j++) 
		{ 
			/* Use a loop to print out the buffer (with %x because it is in hexa): done*/
			printf("%x", outbuf[j]);
		}
		printf ("\n");


		int compare = 0;

		for(int q = 0; q < outlen; q++)
		{
			/* Judge whether the cipher text generated by this key is match for the provided one: done */
			if (outbuf[q] == ciphertxt[q]){
				compare ++;
			}
			/* As the whole ciphertext cannot be matched at once, use this loop to match it bit by bit: done */
			else{
				continue;
			}
		}
		
		if (compare == outlen /* If the generated ciphertext matched with the one provided*/)
		{
			printf ("\n*****************************************************\n");
			
			/* Print the key used (with %s because it is a string): done */
			printf("The key used is: %s\n", key);

			/* Print the text in the buffer: done */
			printf("Buffer: ");
			for(int j = 0; j < outlen; j++) 
			{
				printf("%x", outbuf[j]);
			}
			printf ("\n");

			/* Print the provided ciphertext: done*/
			int i = 0;
			printf("Ciphertext: ");
			while (ciphertxt[i] != '\0'){
				printf("%x",ciphertxt[i]);
				i++;
			};
			printf("\n");

			/* Print the length of the ciphertext: done */
			int cipherLength = i*2;
			printf("The length of the ciphertext is: %i", cipherLength);
			printf ("\n*****************************************************\n");

			return 0;
		} 
	}
	fclose (fp);
	return 0;
}
